### ISSUE TITLE
AttributeError: 'EntryPoint' object has no attribute 'resolve'

### ISSUE THREAD

**Issue by devops** [devops/ansible-rest-api#1]
CentOS 7 Docker环境下运行，报错如下:

[2016-09-23 01:18:15,602: INFO/MainProcess] Received task: celerytask.tasks.ansible_adhoc[93847c8f-d22b-4129-8cc2-65adf1bcc696]
[2016-09-23 01:18:15,755: ERROR/Worker-1] Unknown exception: 'EntryPoint' object has no attribute 'resolve'
[2016-09-23 01:18:15,756: ERROR/Worker-1] Traceback (most recent call last):
[2016-09-23 01:18:15,756: ERROR/Worker-1]   File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1774, in run
[2016-09-23 01:18:15,756: ERROR/Worker-1]     self.kex_engine.parse_next(ptype, m)
[2016-09-23 01:18:15,756: ERROR/Worker-1]   File "/usr/lib/python2.7/site-packages/paramiko/kex_group1.py", line 75, in parse_next
[2016-09-23 01:18:15,756: ERROR/Worker-1]     return self._parse_kexdh_reply(m)
[2016-09-23 01:18:15,756: ERROR/Worker-1]   File "/usr/lib/python2.7/site-packages/paramiko/kex_group1.py", line 111, in _parse_kexdh_reply
[2016-09-23 01:18:15,756: ERROR/Worker-1]     self.transport._verify_key(host_key, sig)
[2016-09-23 01:18:15,756: ERROR/Worker-1]   File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1619, in _verify_key
[2016-09-23 01:18:15,757: ERROR/Worker-1]     key = self._key_info[self.host_key_type](Message%28host_key%29)
[2016-09-23 01:18:15,757: ERROR/Worker-1]   File "/usr/lib/python2.7/site-packages/paramiko/rsakey.py", line 58, in __init__
[2016-09-23 01:18:15,757: ERROR/Worker-1]     ).public_key(default_backend())
[2016-09-23 01:18:15,757: ERROR/Worker-1]   File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/**init**.py", line 35, in default_backend
[2016-09-23 01:18:15,757: ERROR/Worker-1]   File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/**init**.py", line 22, in _available_backends
[2016-09-23 01:18:15,757: ERROR/Worker-1]     # load(), and introduced the new resolve() method instead.
[2016-09-23 01:18:15,757: ERROR/Worker-1] AttributeError: 'EntryPoint' object has no attribute 'resolve'
[2016-09-23 01:18:15,757: ERROR/Worker-1]
[2016-09-23 01:18:15,826: INFO/MainProcess] Task celerytask.tasks.ansible_adhoc[93847c8f-d22b-4129-8cc2-65adf1bcc696] succeeded in 0.222617927s: {'results': [{'play': {'name': u'all', 'id': '34285c14-7d95-49c6-9431-97766fa9fd84'}, 'tasks': [{'task': {'name': u'', 'id':...

**Comment by devops** [comment]
手工解决办法 pip install --upgrade cryptography
