### ISSUE TITLE
运行run.sh报错:KeyError: u'No such transport: sqla' 求助

### ISSUE THREAD

**Issue by raoly** [devops/ansible-rest-api#2]
异常堆栈详情：
app App run in dev mode on 8300
Traceback (most recent call last):
  File "runserver.py", line 61, in <module>
    main()
  File "runserver.py", line 50, in main
    app_server.listen(options.PORT)
  File "/usr/lib64/python2.7/site-packages/tornado-4.4.1-py2.7-linux-x86_64.egg/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib64/python2.7/site-packages/tornado-4.4.1-py2.7-linux-x86_64.egg/tornado/netutil.py", line 194, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/bin/celery", line 9, in <module>
    load_entry_point('celery==4.0.0', 'console_scripts', 'celery')()
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 278, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 241, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 99, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 122, in setup_instance
    self.should_use_eventloop() if use_eventloop is None
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
    self._conninfo.transport.implements.async and
  File "/usr/lib/python2.7/site-packages/kombu-4.0.0-py2.7.egg/kombu/connection.py", line 832, in transport
    self._transport = self.create_transport()
  File "/usr/lib/python2.7/site-packages/kombu-4.0.0-py2.7.egg/kombu/connection.py", line 576, in create_transport
    return self.get_transport_cls()(client=self)
  File "/usr/lib/python2.7/site-packages/kombu-4.0.0-py2.7.egg/kombu/connection.py", line 582, in get_transport_cls
    transport_cls = get_transport_cls(transport_cls)
  File "/usr/lib/python2.7/site-packages/kombu-4.0.0-py2.7.egg/kombu/transport/__init__.py", line 81, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/usr/lib/python2.7/site-packages/kombu-4.0.0-py2.7.egg/kombu/transport/__init__.py", line 62, in resolve_transport
    raise KeyError('No such transport: {0}'.format(transport))
KeyError: u'No such transport: sqla'

**Comment by devops** [comment]
you need use celery 3.x
